apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.config.name }}
  labels:
    {{- include "route-timeout-validator.labels" . | nindent 4 }}
data:
  secondsTimeout: {{ .Values.config.secondsTimeout | quote }}