apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "route-timeout-validator.fullname" . }}-manager-rolebinding
  labels:
  {{- include "route-timeout-validator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "route-timeout-validator.fullname" . }}-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "route-timeout-validator.fullname" . }}-controller-manager
  namespace: {{ .Release.Namespace }}